# Generated by Django 2.2.1 on 2019-05-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='question_text',
            new_name='reading_text',
        ),
    ]
