# Generated by Django 2.2.1 on 2019-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20190530_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='correct_answer',
            field=models.TextField(default='text', max_length=300),
        ),
    ]
