# Generated by Django 2.2.1 on 2019-06-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_multiplechoice_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truefalse',
            name='is_it_false',
        ),
    ]
