# Generated by Django 2.2.1 on 2019-08-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_truefalse_is_it_false'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='correct_answer',
        ),
    ]
