# Generated by Django 2.2.1 on 2019-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_multiplechoice_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_response',
            field=models.TextField(default='Great!', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_response',
            field=models.TextField(default='Not Great...', max_length=300),
        ),
    ]
