# Generated by Django 2.2 on 2019-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='choice_1',
            new_name='correct_choice',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='correct',
            field=models.BooleanField(default=True, verbose_name='Were they correct?'),
        ),
    ]
