# Generated by Django 2.2 on 2019-05-07 13:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_auto_20190502_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date answered'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Were they correct?'),
        ),
        migrations.CreateModel(
            name='UserBelts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notches_complete', models.PositiveSmallIntegerField(null=True)),
                ('belt_complete_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion date:')),
                ('belt_complete', models.BooleanField(default=False, verbose_name='Belt complete?')),
                ('belt_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.BeltLevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
