# Generated by Django 2.2 on 2019-05-07 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20190507_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbelts',
            name='belt_complete_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Completion date:'),
        ),
    ]
