# Generated by Django 2.2 on 2019-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20190507_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbelts',
            name='belt_complete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion date:'),
        ),
    ]
