# Generated by Django 2.2.1 on 2019-05-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20190508_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beltlevel',
            options={'ordering': ['belt_rank']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Question Categories'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['belt_level', 'category', 'qtype'], 'verbose_name_plural': 'All Questions'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name_plural': 'Ranking Questions'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Rating Questions'},
        ),
        migrations.AlterModelOptions(
            name='truefalse',
            options={'verbose_name_plural': 'True False Questions'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name_plural': 'User Answers'},
        ),
        migrations.AlterModelOptions(
            name='userbelts',
            options={'verbose_name_plural': 'User Belts'},
        ),
    ]
