# Generated by Django 2.2.1 on 2019-05-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20190509_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
