# Generated by Django 2.2.1 on 2019-05-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_delete_useranswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBelts',
        ),
    ]
