# Generated by Django 2.2.1 on 2019-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_delete_userbelts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='correct_choice',
            new_name='choice_1',
        ),
        migrations.AddField(
            model_name='truefalse',
            name='is_it_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='truefalse',
            name='is_it_true',
            field=models.BooleanField(default=False),
        ),
    ]
