# Generated by Django 2.2.1 on 2019-05-21 18:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0011_delete_useranswer'),
        ('belts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date answered')),
                ('correct', models.BooleanField(default=False, verbose_name='Were they correct?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Answers',
            },
        ),
    ]
