# Generated by Django 2.2.1 on 2019-05-21 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_delete_userbelts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('belts', '0002_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBelts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notches_complete', models.PositiveSmallIntegerField(null=True)),
                ('belt_complete_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion date:')),
                ('belt_complete', models.BooleanField(default=False, verbose_name='Belt complete?')),
                ('belt_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.BeltLevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Belts',
            },
        ),
    ]
