# Generated by Django 2.2.1 on 2019-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0004_userbelts_notches_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbelts',
            name='notches_override',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
