# Generated by Django 2.2.1 on 2019-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0006_auto_20190524_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbelts',
            name='notches_complete',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
