# Generated by Django 2.2.1 on 2019-08-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0007_auto_20190524_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbelts',
            options={},
        ),
        migrations.RemoveField(
            model_name='userbelts',
            name='notches_override',
        ),
        migrations.AddField(
            model_name='userbelts',
            name='notch_bonus',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
