# Generated by Django 2.2.1 on 2019-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0008_auto_20190801_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbelts',
            name='percent_complete',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
