# Generated by Django 2.2.1 on 2019-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0005_auto_20190523_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbelts',
            name='percent_complete',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='userbelts',
            name='notches_complete',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
